# Generated by Django 2.2 on 2021-09-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useer',
            old_name='email',
            new_name='username',
        ),
    ]
