# Generated by Django 2.2 on 2021-08-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='prdct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('avialable', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categ')),
            ],
        ),
        migrations.RemoveField(
            model_name='prod',
            name='category',
        ),
        migrations.DeleteModel(
            name='sample',
        ),
        migrations.DeleteModel(
            name='prod',
        ),
    ]
