# Generated by Django 2.2 on 2021-08-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210824_2113'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carts',
            new_name='cart',
        ),
        migrations.RenameModel(
            old_name='cartitems',
            new_name='cartitem',
        ),
    ]
